### ISSUE TITLE
Submit Homebrew formula to core

### ISSUE THREAD

**Issue by zmwangx** [soimort/translate-shell#106]
Would you mind if I submit this project to Homebrew core? That would provide at least three benefits:
1. (Biggest user-facing benefit) Auto upgrade. A formula installed via a remote .rb file won't be upgraded when `brew upgrade --all` is run. The only way to upgrade AFAIK is to manually reinstall, so for users who don't follow the project's releases closely, chances are good that it will never be upgraded.
2. Basic tests are run on Brew Test Bot to ensure a release works on OS X before distributing to users;
3. You could take this thing off your shoulder. I subscribe to translate-shell's release feed, so I (or anyone else interested) can update the core formula reasonably soon after each release. (I already keep several other core formulae updated, and so far I've been doing a decent job, typically updating the formula hours within a release.)

If you approve, I'll submit the following to core:

``` ruby
class TranslateShell < Formula
  desc "Command-line translator using Google Translate and more."
  homepage "https://www.soimort.org/translate-shell"
  url "https://github.com/soimort/translate-shell/archive/v0.9.3.1.tar.gz"
  sha256 "7b5a2404ead919570cfa4d741c521ed7e124bbf27d6f5de1a6a598e7e713c2a6"
  head "https://github.com/soimort/translate-shell.git", :branch => "develop"

  depends_on "fribidi"
  depends_on "gawk"
  depends_on "mplayer"
  depends_on "rlwrap"

  def install
    system "make", "PREFIX=#{prefix}"
    system "make", "test"
    bin.install "build/trans"
    man1.install "man/trans.1"
  end

  test do
    assert_equal shell_output("#{bin}/trans -b -s fr -t en bonjour"), "Hello\n"
  end
end
```

A few notes:
1. I shortened the description because `desc` + formula name should not exceed 80 characters in length;
2. I'm calling `bin.install` and `man1.install` to manually install the binary and man page because the `install` target doesn't work on OS X (OS X uses a very old version of `install` that doesn't have `-D`);
3. I'm making `fribidi` a dependency (contrary to https://www.soimort.org/translate-shell/translate-shell.rb where `fribidi` is marked as optional) because (1) `fribidi` is lightweight so it doesn't hurt; (2) I don't see how `fribidi` is more optional than the other dependencies.

**Comment by zmwangx** [comment]
On second thought, mplayer is actually a big dependency (27.5M), so the formula could be improved to let users choose their text-to-speech engine and utilize existing installations (e.g. I already have mpv installed so I don't need mplayer), if they care about text-to-speech functionality at all:

``` ruby
  option "with-espeak", "Use eSpeak for Text-to-Speech"
  option "with-mpg123", "Use mpg123 for Text-to-Speech"
  option "with-mplayer", "Use mplayer for Text-to-Speech"
  option "with-mpv", "Use mpv for Text-to-Speech"

  depends_on "fribidi"
  depends_on "gawk"
  depends_on "rlwrap"

  depends_on "espeak" => :optional
  depends_on "mpg123" => :optional
  depends_on "mplayer" => :optional
  depends_on "mpv" => :optional
```

**Comment by soimort** [comment]
The reason I have chosen not to submit the formula to Homebrew myself is simple: it seems they do not utilize an autonomous registry, other than the centralized GitHub repo. Package maintainers will need to fork the repo, send a pull request every time a new release is made. This process is so laborious that I chose not to do it (otherwise I could have just written a script to automate the task, but `git pull / rebase` and replying to comments will need extra human intervention). Of course, if someone volunteers to maintain the package, that would be very cool and I see no reason not to approve it.
1. It's ok to mark `fribidi` as a hard dependency. Marking `mplayer` as optional is also fine with me (I didn't put too much thought into this, since `mplayer` has been around on my system for quite a while thus it's more like a "legacy thing" to me).
2. Now it came to me that manually invoking `make` in the install target would be a neat idea (so that we can use GitHub archived releases directly);
3. `make test` isn't a must, though. (actually **you should remove `make test` from the formula, it will fail on systems without `emacs` installed!**)
4. It seems that you've removed the `version` field. I'm not sure about this, just asking: is this field necessary? (because it seems to me that there would be no other way for `brew` to reliably tell the version of a formula.)

While you can submit a different version of `translate-shell.rb` to Homebrew core (and hopefully, get accepted), preferably we should keep two formulae identical. Please let me know your final version when you're done, or even better, send me a patch to the `gh-pages` branch of the repository, to this file: [`translate-shell.rb.temp`](https://github.com/soimort/translate-shell/blob/gh-pages/translate-shell.rb.temp).

(As you may see, the formula is automatically generated from a template whenever I tag a release; I had `build.awk` to handle these tedious things, so I never had to touch `translate-shell.rb` myself. If we agree on one single formula, you may just `wget` the same thing and update it accordingly in the Homebrew core, for future releases.

Thanks for taking your time on this!

**Comment by zmwangx** [comment]
> Of course, if someone volunteers to maintain the package, that would be very cool and I see no reason not to approve it.

Actually I already have this in my personal tap, and need to update it whenever a new release comes out, so submitting to core and updating there won't be much extra work for me either. And when submitted to core only one person needs to do the work for each release, so it's good for everyone.

> since mplayer has been around on my system for quite a while thus it's more like a "legacy thing" to me

MPlayer is also legacy to me, but I abandoned it a long time ago (used mplayer2 for a while, then switched to mpv when mplayer2 went dark), so now it feels kinda weird to have MPlayer around since I use it for absolutely nothing... Anyway, I'm not really sure if having a big list of optional dependencies for the same purpose is a good idea. Will ask for Homebrew maintainers' opinions.

> `make test` isn't a must, though.

Yep, know that. The reason I'm invoking it in the `install` block is because `test.awk` is removed after installing, so if I want to run the builtin tests at all, I need to run them here.

> you should remove `make test` from the formula, it will fail on systems without emacs installed!

Does it work with Emacs 22.1 which comes with all relatively recent versions of OS X? Anyway I probably should still remove it to accommodate Linuxbrew users.

> It seems that you've removed the version field. I'm not sure about this, just asking: is this field necessary? (because it seems to me that there would be no other way for brew to reliably tell the version of a formula.)

Most (if not all) core formulae don't have a version field, because version is automatically deduced from download URLs (note that I'm using https://github.com/soimort/translate-shell/archive/v0.9.3.1.tar.gz, where the version is obviously 0.9.3.1). These days, if core can't deduce the version from a URL, either another URL is used or the core is updated to accommodate a new URL scheme. A "latest" URL like http://www.soimort.org/translate-shell/translate-shell.tar.gz won't be accepted into core since the formula is bound to break whenever the remote file is updated, and you can't install an old version by checking out an earlier commit.

> preferably we should keep two formulae identical.

Do you intend to keep https://www.soimort.org/translate-shell/translate-shell.rb even if accepted into core? IMHO you can just update the installation instructions to `brew install translate-shell` and be done with it? As I said installing via https://www.soimort.org/translate-shell/translate-shell.rb doesn't provide self-upgrade, so it's really bad user experience. Also, offloading to core potentially reduces Homebrew-related support burden (although a quick search in the issue tracker indicates that this support burden is practically zero).

**Comment by soimort** [comment]
> Does it work with Emacs 22.1 which comes with all relatively recent versions of OS X? Anyway I probably should still remove it to accommodate Linuxbrew users.

I really don't know, but GNU Emacs 22.1 seems very outdated to me (I'm on 24.5 and don't care about Emacs 22 or 23 support). You will not need `make test` anyway; I did those tests just to keep myself on track (because AWK programming engages a lot of pitfalls). It makes perfectly no sense for normal users (if they don't care about the code at all).

> Most (if not all) core formulae don't have a version field, because version is automatically deduced from download URLs

That explains a lot, thanks!

> Do you intend to keep https://www.soimort.org/translate-shell/translate-shell.rb even if accepted into core?

I'm inclined to keep it, since it'll be updated immediately (after each release) without any delay, although it won't take too long before the change lands on Homebrew core (I hope so). Another reason I'd keep this is because Linuxbrew has a 2-tier delay (other than the downstream delay of Homebrew core); sometimes I have to modify a formula manually to get the latest version of a package. Having a self-hosted formula would take the fuss out of it (in case the brew ecosystem doesn't have an ideal response time, impatient users might want to grab the new formula themselves; I myself used to do that quite often).

Of course, the instruction on the homepage will be changed to

```
$ brew install translate-shell
```

That's a sure thing, as long as it's in the official Homebrew core. (then probably a link to the self-hosted formula)

**Comment by zmwangx** [comment]
Submitted https://github.com/Homebrew/homebrew/pull/49646.

> GNU Emacs 22.1 seems very outdated to me (I'm on 24.5 and don't care about Emacs 22 or 23 support).

It _is_ extremely outdated (from 2007), but 22.1 isn't an accident, since it is the last GPLv2 release of Emacs. I just temporarily unlinked my 24.5.1 install, leaving 22.1.1 as the only version to be picked up, and the tests still passed, so it may well be compatible. Anyway, I've removed the `make test` line.

> I'm inclined to keep it

Sure, makes sense.

> Linuxbrew has a 2-tier delay

Yeah I can testify, been bitten many times personally. Actually, if memory serves, toward the end of the last year there was a one or two-month period when the maintainer was away and not a single commit was pulled from core... It was the worst.

> in case the brew ecosystem doesn't have an ideal response time, impatient users might want to grab the new formula themselves

The ideal response in that scenario is to simply submit a PR; it pains me whenever I see a formula that's not updated in months (and somehow manage to break and block formulae I care about on the CI), and I (as well as maintainers) take that as a strong cue that no one really uses or cares about that formula. Of course I do realize that forking Homebrew and submitting PRs could be too much trouble for folks who don't intend to contribute regularly.

**Comment by soimort** [comment]
> The ideal response in that scenario is to simply submit a PR; it pains me whenever I see a formula that's not updated in months (and somehow manage to break and block formulae I care about on the CI), and I (as well as maintainers) take that as a strong cue that no one really uses or cares about that formula. Of course I do realize that forking Homebrew and submitting PRs could be too much trouble for folks who don't intend to contribute regularly.

That's exactly the part I don't like about brew.

Having a hosting service in which users can upload packages (like PyPI, Hackage or AUR) other than relying on the GitHub's pull request workflow was something I hoped for, at least it would ease the life of package owners without having to do PRs; but that's another story.

Fingers crossed for it all goes well.

**Comment by zmwangx** [comment]
> Having a hosting service in which users can upload packages (like PyPI, Hackage or AUR) other than relying on the GitHub's pull request workflow was something I hoped for, at least it would ease the life of package owners without having to do PRs; but that's another story.

I contest this with several arguments:
1. Only the software author and/or maintainer can submit to PyPI, Hackage, AUR or whatever popular package index, whereas anyone can submit any package to Homebrew core as long as it's somewhat notable (e.g., 20 stars on GitHub), and self-submission is actually discouraged, although once accepted maintainers could submit updates if they'd like to (there's no stopping you from having a tap or just a .rb file — those are sort of like PPAs). This community-driven nature is solely responsible for the inclusion  of (I suppose) most packages where the author and/or maintainer won't ever submit themselves. (Can you imagine FSF submitting coreutils to Homebrew? And most smallish Linux-oriented projects?)
2. Homebrew reviews all commits for dangerous hacks and pitfalls, and tests them for build failures and basic functionality problems against three most recent major OS releases before committing to master, which greatly reduces failures on users' part. Most smallish projects don't have this sort of testing resources (especially not on OS X), and meanwhile, there's no quality check whatsoever on most help-yourself package indices.
3. Homebrew provide binary packages (called bottles) for most packages on the three most recent major OS releases. This is not possible on many package indices, and even for package indices that support binary distributions, e.g. PyPI, those are usually self-uploaded, few and far between (because most people don't know how or don't bother or technically can't as they don't have access to the target OS) and generally less trustworthy.

Admittedly GitHub's PR workflow isn't the best, but a help-yourself package index is the last thing I would like to see in Homebrew's case.

**Comment by zmwangx** [comment]
Correction: My first bullet point might not precisely describe AUR, but still, having a fixed maintainer for each package may not be a great idea, especially not for Homebrew.

**Comment by soimort** [comment]
1. Just to clarify, I agree with you on that quality control is best with Homebrew. AUR is nothing like that (as a longterm Arch user: I actually doubt whether many Arch `community` packages have undergone sufficient quality reviews). So it's more like Debian on the quality side, but anyone has access to GitHub can submit and update packages via PRs.
2. By discouraging authors submitting their own projects, Homebrew prevents itself from gibberish packages and name squatting, and that is a good thing; but I can also imagine that some kinda useful tools (like this one) would not enter its ecosystem until someone enthusiastic (like you) comes up and is willing to maintain it. Meanwhile, if you authored a package on PyPI, npm, RubyGems, Hackage, you have the full control of it and any user will get immediate access to it - surely there's a risk they must take, but if they trust your code - they already did, and they won't need a 3rd party to prove that for you. (Homebrew doesn't review the actually source code of packages, afaik, so it's still based on some level of trust)
3. Another point is for the sake of software freedom and/or decentralization. Currently Homebrew totally relies on GitHub (almost every bit of it); self-hosting package archives do not. Of course, you and I are both on GitHub, so it might not matter that much. In the unlikely event of GitHub going down, everyone would lose access to Homebrew (Correct me if I'm wrong: I don't think there's any mirror of it, so you can't use the Homebrew core if you are unable to access GitHub.)

---

P.S. I don't care for the fixed maintainer model too. Sometimes an AUR package goes outdated (simply because the owner is no longer active but wouldn't orphan the package), you have nothing to do but to wait for enough long time so you can ask administrators to kick the owner out and let you maintain it. The PR model makes more sense in this case, because anyone can take the responsibility of updating a package.

**Comment by zmwangx** [comment]
> By discouraging authors submitting their own projects, ... but I can also imagine that some kinda useful tools (like this one) would not enter its ecosystem until someone enthusiastic (like you) comes up and is willing to maintain it.

To be fair, discouragement of self-submission applies more to projects that barely qualify (say, a GitHub project with exactly 20 stars); for a project with ~1000 stars (like this one) it's usually fine as long as you don't have a history of abuse.

> Meanwhile, if you authored a package on PyPI, npm, RubyGems, Hackage, you have the full control of it and any user will get immediate access to it

That's a fair point. Anyway, there are trade-offs to make.

> Homebrew doesn't review the actually source code of packages, afaik, so it's still based on some level of trust

Yep, upstreams are inherently trusted (and in fact, _only_ upstreams are trusted — downstream patches won't be applied unless upstream is notified, and even then they go under strict scrutiny). Homebrew's review and testing aren't really security screens, they merely ensure there's no (good-faithed) mishandling and no obvious user-facing problems.

> software freedom

I'm not sure if by this you're pointing to the fact that GitHub is closed source. In any case, I'm not a bit concerned about this (those GitHub vs GitLab debates are a waste of time IMO). As long as I have access and rights to the code I care about, I'll just pick the most convenient place to host it, and no one can stop me from migrating if the current platform goes rogue.

> In the unlikely event of GitHub going down, everyone would lose access to Homebrew

Strictly speaking, yes, but I doubt if that's really an issue. Due to git's decentralized nature, as long as you run `brew update` reasonably frequently (say, stick it into a daily cron job), you'll always have a relatively up-to-date copy of the entire history (actually, if you use the supplied installation script you'll get a shallow copy, but let's ignore that detail). Since GitHub is down and development can't happen until either GitHub is restored or development is relocated, you copy will remain relatively up-to-date until development resumes. This is not so different from pypi.python.org going down and PyPI entering a read-only mode through mirrors until service is restored.

The more realistic concern for Homebrew is source packages going dark. Homebrew doesn't host source packages, so if a source package is unavailable then you can't install from source. This unfortunately happens far too often with SourceForge, where a large percent of packages are based.

> I don't think there's any mirror of it

No official mirrors, that's right. A quick search yields a Chinese mirror of both [homebrew.git](https://mirrors.ustc.edu.cn/homebrew.git/) and [homebrew-bottles](https://mirrors.ustc.edu.cn/homebrew-bottles/), updated hourly; I'm sure there are more unofficial mirrors. Of course, I bet homebrew.git can be found on every GitHub decentralization project, say, gittorrent.

**Comment by soimort** [comment]
By "software freedom" I meant preferably an open source project shouldn't rely on a single proprietary service, that is, if the service goes down or inaccessible for some reason, the community could just create another instance (from the open source code) that functions as well. But ehhhh. We all know that _translate-shell has to take advantage of Google's closed source technology for now_. So I'll just let that point slide.

> Homebrew doesn't host source packages, so if a source package is unavailable then you can't install from source.

True. But hosting the source of every package would be way too much for a GitHub repository (even if with Git LFS support). I don't see how this problem can be resolved, unless Homebrew employs its own hosting service. Hopefully most packages are hosted on GitHub, too, so as long as Homebrew is available, they are available.

**Comment by zmwangx** [comment]
>  if the service goes down or inaccessible for some reason, the community could just create another instance (from the open source code) that functions as well.

Since everyone has a full copy of homebrew.git, that should be pretty easy. (To be fair, the issue tracker may not be easily reproduced in case GitHub goes down; I'm not sure if independent GitHub archival projects have all the data.)

> But hosting the source of every package would be way too much for a GitHub repository

Homebrew uses Bintray to host bottles (binary distributions), so source archives at least could be mirrored on Bintray. I don't think it will be a whole lot of work (it will fit into the current publish and download schemes quite easily), but it's probably not worth it, and I'm not passionate about this idea.

In any case I'm not saying source packages occasionally becoming unavailable is a urgent problem. I'm just using it as an example of an actual issue, compared to losing access to GitHub which is almost a non-issue (at least in the short term, and in the long term if anything's wrong solutions could always be figured out).

> Hopefully most packages are hosted on GitHub

As I said, quite some packages are unfortunately hosted on SF which has not only gone rogue in a certain sense but also had pretty disappointing uptime in the recent months.

**Comment by soimort** [comment]
The thread has gone far beyond the scope of this project, so I'll just stop here.

At this point, while we are having some juicy discussion here, the PR on Homebrew did not get a reply (yet). So you see, this model does not always have an ideal response time.

**Comment by zmwangx** [comment]
> So you see, this model does not always have an ideal response time.

True. From my experience I would say that once accepted, minor updates are almost guaranteed to be merged within a day, but that's still less than ideal.

**Comment by soimort** [comment]
> minor updates are almost guaranteed to be merged within a day,

One day isn't _too bad_, I suppose. I'd imagine that this timespan could be problematic when a bug-fix release becomes critical (i.e. as some serious security issue exposes), but it's not that much of our concern (for such a tiny tool like `trans`). We can just wait: )

**Comment by zmwangx** [comment]
Finally my PR has been merged. The formula ended up as https://github.com/Homebrew/homebrew/blob/96dadaa/Library/Formula/translate-shell.rb, where we dropped the list of optional dependencies and instead listed the choices in a caveat.

The template could be

``` rb
class TranslateShell < Formula
  desc "Command-line translator using Google Translate and more"
  homepage "https://www.soimort.org/translate-shell"
  url "https://github.com/soimort/translate-shell/archive/v$Version$.tar.gz"
  sha256 "$sha256$"
  head "https://github.com/soimort/translate-shell.git", :branch => "develop"

  depends_on "fribidi"
  depends_on "gawk"
  depends_on "rlwrap"

  def install
    system "make"
    bin.install "build/trans"
    man1.install "man/trans.1"
  end

  def caveats; <<-EOS.undent
    By default, text-to-speech functionality is provided by OS X's builtin
    `say' command. This functionality may be improved in certain cases by
    installing one of mplayer, mpv, or mpg123, all of which are available
    through `brew install'.
    EOS
  end

  test do
    assert_equal "Hello\n", shell_output("#{bin}/trans -b -s fr -t en bonjour")
  end
end
```

Not sure if you would like to tweak it a bit for Linuxbrew, or just leave as is. Anyway, `build.awk` will need to be updated to calculate sha256sum instead of / in addition to sha1sum, which should be very easy.

**Comment by soimort** [comment]
Good to know. Thanks for contributing this, @zmwangx!

> By default, text-to-speech functionality is provided by OS X's builtin
> `say` command. This functionality may be improved in certain cases by
> installing one of mplayer, mpv, or mpg123, all of which are available
> through `brew install'.

The caveats make sense only to OS X users. `say` won't be as good as Google's speech engine, and since users can always (simply!) `trans something | say` if they want, I wouldn't say `say` is something interesting enough to emphasize here. However, there seems to be no way to implement the "_Exactly-one_" semantics for optional dependencies (`mplayer`, `mpv`, or `mpg123`) in Homebrew, so I'd keep those caveats as they're.

``` ruby
  assert_equal "Hello\n", shell_output("#{bin}/trans -b -s fr -t en bonjour")
```

A trivial but subtle issue: When running this line on a development machine, on which users have their own `.trans` configuration (probably with a theme), the test for equality may fail, because the output may involve some user-defined ANSI color codes. Adding either `-no-init` or `-no-ansi` option will fix that. That's not so relevant for running tests on the sandbox of CI, though.

I will update README to reflect the inclusion of trans as an offical Homebrew formula later on.

**Comment by zmwangx** [comment]
> The caveats make sense only to OS X users.

Correct, that's why I said you might want to modify this for Linuxbrew users.

> `say` won't be as good as Google's speech engine

Yes, and it's limited to certain languages; for instance, every single Chinese character is pronounced "CJK Unified Ideograph"... It could be better in certain ways when it works, though. At least it's more seamless. I have `force-window` in my `mpv.conf` to force windows for all audio playback (I want to have OSC at all times), and when `trans` uses `mpv` for text-to-speech, I get a series of windows popping up. So each option has potential drawbacks, at least for now.

> I wouldn't say say is something interesting enough to emphasize here.

I just wanted to point out that even if you don't install any additional dependency, text-to-speech still works (on OS X).

> A trivial but subtle issue

Tests are usually geared towards default install options and default configurations (I once tried to fix `findutils`'s test for `--default-names` but was rejected), so I'd say it's a non-issue — tests are not designed to work for everyone in every situation. However, since it's easy to fix in this case, I'll incorporate the option in the next update to the formula.

**Comment by soimort** [comment]
> I will update README to reflect the inclusion of trans as an offical Homebrew formula later on.

Done. I'm closing the issue.

Thanks again for taking your time!
