### ISSUE TITLE
Short option for -verbose

### ISSUE THREAD

**Issue by alexreg** [soimort/translate-shell#122]
It would be nice to have a `-v` short option equivalent to `-verbose`.

Also, is there any particular reason that short and long options are both prefixed by `-` and not the GNU/Unix convention of `--` for long options?

**Comment by soimort** [comment]
1. `-v` was reserved for `-view`, i.e., the short way to launch a pager (`less`). Users are not expected to invoke the dummy `-verbose` option at all, since everything's already verbose by default. (unless you've set the default to brief mode in your configuration file)
2. No, not any particular one that I can think of. However, for some options commonly used by myself, such as `-id`, `-no-ansi`, I failed to find a proper single letter to assign to each of them; thus typing `-id` would save one keystroke than `--id`.

You may still prefix all options with `--`, if you prefer the long way; albeit the combination of short options is not possible.

**Comment by alexreg** [comment]
Thanks for the reply. Re 1, I do indeed have brief mode set by default in my config file. Re 2, fair enough.

**Comment by soimort** [comment]
Re: Re 1, if you want to use brief mode as default but also need verbose translations quite often, just do something like `alias trans-v='trans --verbose'`. That'd be as good as you need it.

**Comment by alexreg** [comment]
Good idea, thanks.
