### ISSUE TITLE
Trans has stopped working?

### ISSUE THREAD

**Issue by rr-** [soimort/translate-shell#123]
Input:

``` console
rr-@tornado:~$ for engine in google bing yandex apertium; do \
    echo "$engine"; \
    trans -f en -t ja -e $engine -no-init -verbose "just testing"; \
done
```

Output:

```
google

bing
[ERROR] Oops! Something went wrong and I can't translate it for you :(
yandex
[ERROR]

apertium
just testing



[ English -> 日本語 ]
```

Version:

```
Translate Shell       0.9.3.2-git:6cf6a1e

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.7
audio player          mpv
terminal pager        less
terminal type         rxvt-unicode-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
```

EDIT: judging from my command history, it has worked as far as 15:07 CET without me doing any change to the OS.

**Comment by soimort** [comment]
Confirmed.

Google updated its encryption method. Bing changed its API (completely). Didn't look at Yandex yet, but obviously the old hack is not working anymore.

**Comment by scturtle** [comment]
The algorithm to compute `tk` mentioned in #94 has been changed a bit.
It seems that now you need to extract some magic numbers from html and `^` it with a.

``` python
import re
import sys
import ctypes
try:
    import urllib2 as request
except:
    from urllib import request


def get_d1():
    req = request.Request(url='http://translate.google.com/', headers={'User-Agent': 'Mozilla/5.0'})
    t = request.urlopen(req).read().decode('utf8')
    a, b, h = re.search(r"TKK=eval\(\'\(\(function\(\){var a\\x3d(\-?\d+);var b\\x3d(\-?\d+);return (\d+)", t).groups()
    return int(h), ctypes.c_int32(int(a) + int(b)).value
b, d1 = get_d1()


def RL(a, b):
    for c in range(0, len(b)-2, 3):
        d = b[c+2]
        d = ord(d) - 87 if d >= 'a' else int(d)
        xa = ctypes.c_uint32(a).value
        d = xa >> d if b[c+1] == '+' else xa << d
        a = a + d & 4294967295 if b[c] == '+' else a ^ d
    return ctypes.c_int32(a).value


def calc_tk(a):
    if sys.version_info >= (3,):
        d = a.encode('utf-8')
    else:
        d = map(ord, a)
    a = b
    for di in d:
        a = RL(a + di, "+-a^+6")
    a = RL(a, "+-3^+b+-f")
    a = ctypes.c_int32(a ^ d1).value
    a = a if a >= 0 else ((a & 2147483647) + 2147483648)
    a %= pow(10, 6)
    return '%d.%d' % (a, a ^ b)

if __name__ == '__main__':
    text = ' '.join(sys.argv[1:])
    print(calc_tk(text))
```

**Comment by soimort** [comment]
I've been collecting the TKK values via a phantomjs script during the past few hours.

```
406390.189688973
406391.2137922361
406392.3194828186
406393.4276332215
406394.2641390264
406395.1620790940
406396.668111980
406397.1556704340
406398.2087938574
406399.1216016228
406400.3697364690
406401.299565202
406402.1406994857
406403.1796542001
406404.1046340058
406405.1972782104
406406.2841541325
406407.1912767145
406408.798059552
406409.178026532
406410.2691268540
406411.3119858813
406412.2024202662
406413.200884332
406414.2908705488
406415.2644941540
406416.489912402
406417.1294474066
406418.3614684883
406419.37275125
406420.3004485997
406421.1121578799
406422.3377234001
406423.4167013162
406424.135695242
```

I don't know what the second value is; but I'll see if there's a way to reverse-engineer the mapping function.

**Comment by ticki** [comment]
I experience this too. I believe Google has changed their API. It seems to be broken with Yandex and Bing as well.

**Comment by ticki** [comment]
Is the Google reversed engineered "API" documented somewhere?

**Comment by soimort** [comment]
**Updates: (as of May 14, 2016)**
1. I believe the second part of TKK came from a common crypto hash (on the Unix epoch hour no.) under some transformation, however I just can't figure it out (yet).
2. While the fix would be quite easy if you do a match on the HTML page of `translate.google.com`, as @scturtle suggests, this is not feasible in pure AWK, because
   1. http://translate.google.com seems to use HTTPS exclusively. (I'm not sure why the `?nord=1` parameter doesn't do the trick)
   2. gawk's networking implementation isn't aware of SSL/TLS at all. (TCP socket only!)

The kludge here is to call `curl` or `openssl` for secured access, but that would yield another considerable overhead; After all, a 200k web page isn't quite trivial ((to fetch and extract every time). So ideally the TKK should be cached for later use during its lifespan (~1h).

**Comment by rr-** [comment]
Maybe we could reach out to Google and ask them to implement real solution to secure their API such as rate limiting, rather than silly tricks like this?

I mean, the moment Google generates server-side random tokens that client must send back and combines it with hardcore JS obfuscation, the party's over anyway, and it certainly looks like we're headed in that direction...

**Comment by soimort** [comment]
> Maybe we could reach out to Google and ask them to implement real solution to secure their API such as rate limiting, rather than silly tricks like this?

Per IP basis?

I see your point, but Google Translate API isn't free at all, i.e., they don't want _any unpaid access_ to their service. That's why rate limiting is usually applied per registered API token, not per IP, otherwise anyone can just build their apps upon Translate API without paying Google anything.

So I can totally understand why they're not ok with us doing it.

Plus, they have enough of silly tricks like this AFAIK, if you look at how they obfuscate the JS on YouTube. Fortunately, every time they roll out new tricks like this, we'll eventually find a way to circumvent it (sometimes suboptimally).

**Comment by Anoncheg1** [comment]
Hi
[google translator](https://github.com/Anoncheg1/Command-line-translator/issues/10)
**There is mystic TKK here:**

```
Interval 1 minute
a,b,    bash:   $((`date +%s`/3600))

1790737538 1038178289 406454
2986620395 -157704568 406454
4058962514 -1230046687 406454
639923482 2188992345 406454
1924343731 904572096 406454
1127955721 1700960106 406454
```

**Comment by soimort** [comment]
A solution has already been proposed in an earlier comment https://github.com/soimort/translate-shell/issues/123#issuecomment-218647599.

Unless you have a better solution which **does not require scraping the whole HTML page**, please use +1 instead of "me too" posts or repeating the existing algorithm here.

**Comment by CoolAller** [comment]
soimort, Where to insert this algorithm?

**Comment by soimort** [comment]
All done.

Note: Apertium doesn't even support Japanese anyway, so that one's not our (resolved) issue.

**Comment by admirabilis** [comment]
Thank you for having fixed this so fast!

I have just a small suggestion to avoid problems in the future! I don't really know how this extension works, and I'm sorry if it implements the translation in a non-practical manner, but I have https://addons.opera.com/pt/extensions/details/xtranslate/ installed in my browser, and while translate-shell stopped working, the extension continued working without any problems, and it was not updated!

**Comment by sandrolemosmachado** [comment]
Hi, trans has no output here. how can I implement the algorithm to compute tk ?
