### ISSUE TITLE
+1 #123

### ISSUE THREAD

**Issue by zetok** [soimort/translate-shell#124]
> Unless you have a better solution which does not require scraping the whole HTML page, please use +1 instead of "me too" posts or repeating the existing algorithm here.

Since it's not possible to +1 anyone in #123 (since it's locked), I'll just +1 myself here.

Cheers :)

![tfw no +1](https://cloud.githubusercontent.com/assets/3148759/15305800/556ff764-1bbd-11e6-80c9-cdb69f1729af.png)

**Comment by soimort** [comment]
Thanks for noticing -- however, please check out first the latest git branch to see if everything works out for you. Also, there's no need to spam everyone who subscribed to receive material updates on the fix (since we all already knew about the issue).

You're welcome to open another issue on that, but only with real suggestions and / or pull requests: )
