### ISSUE TITLE
Better support for non-gvim users

### ISSUE THREAD

**Issue by DanielAndreasen** [soimort/translate-shell#13]
This is my first issue ever on github, so apologizes if I do this wrong.

I implemented the vim-hack, and it is working fine. However, I do not use gvim, but normal vim in the terminal. When I press <Shift>-K vim goes to the terminal windows and shows me the translate rather than showing it inside vim at the bottom, as your nice example gif shows. However, when using gvim, it is working fine.
Any advice to get this working? :)

![screenshot from 2014-03-13 17 33 56](https://f.cloud.github.com/assets/4519017/2412711/cd81cd1e-aad5-11e3-9dfd-b7629056133e.png)
![screenshot from 2014-03-13 17 33 37](https://f.cloud.github.com/assets/4519017/2412712/cd828628-aad5-11e3-8871-32e42e1a903e.png)

The two pictures shows an example. After I hit Enter, I return normally to vim.

Cheers,
Daniel

**Comment by soimort** [comment]
There's no such thing like "Vim support" here. `translate.awk` is in no way a Vim or any editor's plugin. Remember it is just a **command line program**. And how it behaves depends on how you want to use them and how you configure them in your text editor.

The `K` command runs the external program configured by `keywordprg` and displays its output outside Vim. This is the default behavior of `vim`, but not `gvim`. If you want to show it inside Vim, a plugin like `ftplugin/man.vim` will do that for you. You may also want to map your preferred key to that.
This article may help: http://usevim.com/2012/09/07/vim101-keywordprg/

I can't provide more help on vim since I don't use it anymore; but surely you can figure this out.
