### ISSUE TITLE
Google Translate recognises country code but not Translate Shell

### ISSUE THREAD

**Issue by dnicolson** [soimort/translate-shell#135]
The country code "DE" is not recognised by Translate Shell using the following command `trans -t DE "happy go lucky" -e google`:

> [WARNING]` Unknown target language code: DE
> happy go lucky
> 
> glücklich gehen
> 
> Definitions of happy go lucky
> [ English ->  ]
> 
> adjective
>     sorglos
>         carefree, careless, unmindful, unworried, jaunty, happy-go-lucky

Specifying the full name "Deutsch" results in the same output, except there is no unknown language code warning and "Deutsch" appears after the "->" characters. Only Google Translate successfully translates, the other three engines do not.

`trans -V` output:
Translate Shell       0.9.4

> platform              Darwin
> gawk (GNU Awk)        4.1.3
> fribidi (GNU FriBidi) 0.19.7
> audio player          mplayer
> terminal pager        less
> terminal type         xterm-256color
> user locale           en_US.UTF-8 (English)
> home language         en
> source language       auto
> target language       en
> translation engine    google
> proxy                 [NONE]
> user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
> theme                 default
> init file             [NONE]

**Comment by soimort** [comment]
This looks like an expected behavior.

The official recommendation for ISO 639 language codes is to use **_lowercase**_ letters exclusively (although not strictly as a specification).

Despite that Google Translate does support uppercase codes like `DE`, it doesn't mean uppercase is recommended; plus Bing and Yandex will not recognize those language codes in their APIs. Thus, `trans` is following the lowercase convention (to make all translation engines happy).

**Comment by hamadaspace** [comment]
the underscore is the problem!
try `lang.replace('_','-')`  
en-us or en-US but not en_us or en_US .
