### ISSUE TITLE
[Feature Request] Ability to clear the console output in Interactive mode

### ISSUE THREAD

**Issue by letientai299** [soimort/translate-shell#145]
I'm using Zsh with Oh-my-zsh installed.

In `-I` mode, when I press `Ctrl-L`, `trans` just show `^L` and the console is not cleared.
I have tried to run `trans` with `bash`. It's the same behavior. So I guess this feature is not implemented. Meanwhile, `^C` is handled very well (It stop after print `^C`).

Please consider adding this feature. This would be very helpful for someone read a long paper and use `trans -I` as a dictionary.

**Comment by soimort** [comment]
[rlwrap](http://utopia.knoware.nl/~hlub/uck/rlwrap/#rlwrap) is listed as one of "recommended dependencies". As long as `rlwrap` is found in your path, `trans` will invoke that (which enables better terminal editing).

AWK does not have its own readline binding, so it would be unnecessarily cumbersome to implement one (if not impossible). I'm not going to do this, since rlwrap already covered everything (keybindings for termcap codes such as `^L`, Emacs style line-editing, history navigation, etc.).

**Comment by cromatikap** [comment]
Hi there, 
I need some clarifications about history. I installed rlwrap (and the command works) but when I `$ trans -I`, it seems to have the same behavior than before. Perhaps I misunderstand what "history" means. I expect to be able to find back my old translations with up/down arrow keys like usual command bash history, but instead, it only prompts `^[[A` or `^[[B` depending on the arrow.
Is this feature available ? (if not, it would be a really good idea :smiley:  )

Btw, awesome program which save my life every single day :+1:

**Comment by soimort** [comment]
@axel-lasseur This is an old bug, fixed by f4ac7f6ab03933d589e365008678a273c3fefde7.

A new release should be underway, but you can grab `develop` branch from git if you need it now.
