### ISSUE TITLE
Issue with google based YUE translations.

### ISSUE THREAD

**Issue by abhi18av** [soimort/translate-shell#185]
Hello @soimort ,

I've noticed that the following program doesn't work

```sh
❯ trans en:yue "Hello, world!"

```

However, the following works fine 

```
❯ trans en:yue "Hello, world" -engine=bing
Hello, world

世界你好

[ English -> 粵語 ]
```

I guess, it's a minor bug or something since google **does not** support it  but trans shell doesn't throw errors or warnings, as in the case of yandex

```sh
❯ trans en:yue "Hello, world" -engine=yandex
[ERROR] The specified translation direction is not supported

```

**Comment by soimort** [comment]
It's actually the intended behavior.

Google Translate API does not throw any error when an unrecognized language code is encountered; from previous experience, experimental (undocumented) language support is added from time to time. Since Google Translate doesn't consider new code as an error, there's no point to impose it on our side.

Bing and Yandex API, however, **do** raise an error for unrecognized languages; that's why.

**Comment by abhi18av** [comment]
I understand and appreciate your quick response @soimort  :+1: 

Thanks.
