### ISSUE TITLE
Use `gawk` not `awk` in Mac OS X

### ISSUE THREAD

**Issue by douglarek** [soimort/translate-shell#2]
Hi @soimort ,

Default `awk` in Mac OS X is not `gawk`, will you improve the Compatibility and give an OS judgement? I am not Familiar with `awk` .

Thanks,

**Comment by soimort** [comment]
Since the path of `gawk` differs in various OSes, `/usr/bin/env` will be needed in the shebang. On BSD variants, you can pass `gawk -f` directly to it and write things like:

``` sh
#!/usr/bin/env gawk -f
```

This also works pretty well for Gawk from MacPorts.

Unfortunately, because kernel developers are sticking to a lame design, the above shebang will not work on Linux. That is why I used `#!/usr/bin/awk -f` and thus incompatible with OS X.

I may add some autotools OS detection later though.

**Comment by douglarek** [comment]
@soimort yeah, thanks for this
