### ISSUE TITLE
Lists unavailable engine(s)

### ISSUE THREAD

**Issue by Boruch-Baum** [soimort/translate-shell#228]
The list of engines presented to me when running `trans -S` included `hunspell`, but when I tried using that engine, the program responded:

    [ERROR] Spell checker (hunspell) not found.

Which seems reasonable in my case, since that package is not installed locally, but then `trans` should not list it (I thought maybe that the entry referred to some on-line service associated with `hunspell`).

**Comment by soimort** [comment]
`trans` is supposed to list all *currently implemented* engines, regardless of whether or not they are actually usable on the user's machine. (For instance, `google` and `bing` require network access to work, but `trans -S` will not unlist them because of network failures.)

So this seems like a non-issue for me.
