### ISSUE TITLE
gawk error when using aspell engine

### ISSUE THREAD

**Issue by Boruch-Baum** [soimort/translate-shell#229]
When trying to use the `aspell` engine (listed as an entry in `trans -S`), the output error is 

    gawk: /dev/fd/63:3235: fatal: `aspellWebTranslateUrl' is not a function, so it cannot be called indirectly

**Comment by soimort** [comment]
1. Please follow the [bug reporting guidelines](https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md#how-to-report-an-issue) and post the *actual command*, otherwise I may not be able to reproduce your issue.
2. `aspell` uses GNU Aspell locally for spell checking, it won't work with URLs like other (online translation) engines do. I guess that might be the reason if you were expecting to spell-check a web page.

**Comment by Boruch-Baum** [comment]
I missed your original response. Your paragraph '2' clarifies the issue. Maybe have the program trap the raw error message and prompt the user with guidance, something like "the aspell engine can not be used for url translations"
