### ISSUE TITLE
Is translate-shell safe in shell?

### ISSUE THREAD

**Issue by crazywhalecc** [soimort/translate-shell#254]
I need to use pipe to input some translate words, like `echo trans.txt | trans :zh`.
I used `exec("trans :zh ".$word);` before but it's obviously dangerous. 
How can I use `exec()` function in PHP and make it safe? pipe?

**Comment by soimort** [comment]
I don't have much experience with PHP though. If your question is about "How to call a command safely in PHP?" Then you should definitely use something like
```
exec("trans :zh " . escapeshellarg($word));
```
to prevent injections.

Regarding translate-shell itself, I can't be 100% sure that no one can exploit the argument string in an unexpected way, since `trans` also internally calls other command-line utilities (which make security even harder to analyze). If security is your major concern, try to remove special chars from `$word` as well.
