### ISSUE TITLE
Google translate 503 Forbidden

### ISSUE THREAD

**Issue by AdrianSimionov** [soimort/translate-shell#290]
I started today re-using this software after about 6 months and it seems Google now detects the automated requests. Please take a look at the following repo which generates the missing token needed for the detection.

https://github.com/matheuss/google-translate-token

**Comment by AdrianSimionov** [comment]
What is the reason for closing this issue?

**Comment by soimort** [comment]
1. translate-shell has that TK-generating facility [back in 2015](https://github.com/soimort/translate-shell/commit/0f44d138439be3b28b1f4a0470adf43c3a2c5a6f#diff-6ddbac3e5d6aecc40140b780cdfef35e), just no longer used or updated, since we found a token-free API that Google generously allows anyone to use so far, within reasonable limits.
2. If your intention is to benefit from a so-called "free Google Translate API", then you've probably channeled the issue to the wrong place. You should report such issues in your mentioned repository, in case they can function no more.
3. TK is not really an API key since you don't pay for it. Google can still kick you out if you automate too much or too fast, so to say.

I can't help you circumvent Google's rate limits. Sorry about that.

**Comment by AdrianSimionov** [comment]
Look, mate, I think you are pretty rude. But that is fine, inteligent people do that mistake very often. I did read your website and unfortunatelly did not find any article on soft skills, probably is not a topic which is of any interest to you.

I just tried to report a possible improvement or a coding issue, because I am pretty sure you have one.

For example, translate-shell gets forbidden pretty quickly by Google.

Using the following URL does not have the same forbidden state from Google as translate-shell does.

https://translate.google.com/translate_a/single?client=at&dt=t&dt=ld&dj=1&ie=UTF-8&oe=UTF-8&q=

I am using the exact same shell of the same machine.

**Comment by soimort** [comment]
Dear Adrian,


> Look, mate, I think you are pretty rude.

Sorry, didn't mean to hurt your feelings so easily. My apologies.

> I did read your website and unfortunatelly did not find any article on soft skills, probably is not a topic which is of any interest to you.

Sorry about this, but I did not read any of your article on soft skills as well. Should people always write about soft skills to prove they have those?

> because I am pretty sure you have one.

Again, I am deeply sorry if this issue annoys you a lot.

Please feel free to seek help in other places. Or to [pay for Google API](https://cloud.google.com/translate/pricing) to get things done -- To my knowledge, that's the only way you can do it *legally*, without violating their TOS. I am also sorry about that, but there's nothing much I can help here.

Cheers.

Mort

**Comment by soimort** [comment]
Just for your convenience, I found several other projects that claim to offer free unlimited Translate APIs and are still actively maintained until very recently. I can't say I'm endorsing any of these, but please make sure to check them out.

- https://github.com/yixianle/translate-api
- https://github.com/ssut/py-googletrans
- https://github.com/Stichoza/google-translate-php
