### ISSUE TITLE
How do I know whether I have BSD awk or GNU awk?

### ISSUE THREAD

**Issue by airblade** [soimort/translate-shell#3]
Apologies for the silly question.

I'm on OS X.  How do I tell which awk I have?  `awk` doesn't accept `-h` or `--help`.  The only info I can get is:

```
$ awk --version
awk version 20070501
$ which awk
/usr/bin/awk
```

Assuming I have BSD awk, is there any disadvantage to installing GNU awk?

**Comment by soimort** [comment]
It's easy to tell - GNU awk always has a `--help` option. Since you are on OS X and your `awk` doesn't accept `-h`, it should the "original" BSD awk.

GNU awk extended the original AWK in some way (e.g. TCP/IP functionality needed by this script), and kept backward compatibility with legacy code. Not any disadvantage I can think of. It's available via Homebrew or MacPorts.
(won't conflict with the preinstalled `awk` as the name identified by `gawk`)

**Comment by airblade** [comment]
Thanks for the informative answer!
