### ISSUE TITLE
markup handling

### ISSUE THREAD

**Issue by Konfekt** [soimort/translate-shell#302]
Is there somewhere documented how the translator engines translate markup? For example, `translate -no-warn -no-ansi -brief -engine google -to en`on 
```
Como $a^2 + b^2 = 1$, obtemos $a$ e $b$ em $[-1, 1]$.
```
yields
```
Since $ a ^ 2 + b ^ 2 = 1 $, we get $ a $ and $ b $ in $ [- 1, 1] $.
```
Whereas `translate -no-warn -no-ansi -brief -engine yandex -to en` yields
```
As $ a^2 + b^2 = 1$, we get $a$ and $B$ in $[-1, 1]$.
```
and all other engines return nothing. 

Is there a switch to make the markup digestible to particular engines?

**Comment by soimort** [comment]
> Is there a switch to make the markup digestible to particular engines?

Sadly no. If you paste your Markdown text into Google Translate or Yandex's textbox, it is quite often messed up -- And this is not something I can fix, since `trans` is a command-line interface, not a translator on itself.

You need to ask Google or Yandex to add Markdown support to their translators.

**Comment by Konfekt** [comment]
A simple try for users using alphabets extending the Latin one to convert markup into prose, would be a switch that replaces or removes all characters other than `[a-zA-Z0-9]` (and its accented variants given in https://en.wikipedia.org/wiki/Latin_script_in_Unicode) and punctuation marks such as `[.;:!?"']`.

There is probably a conversion script ready at some place; for example, TeXstudio prepares the LaTeX code so that lanuage-tool, which expects pure prose, can handle it.

**Comment by soimort** [comment]
How do you expect `trans` to handle it correctly, then?

In principle one can't just blindly remove exotic characters from texts since that would change their original semantics (for example, "`$`" could also stand for "dollar").

Of course, if you already know that the text you're going to translate is in Markdown (or LaTeX, etc.) format, then it is quite easy to use a conversion tool (such as `pandoc`) to convert it to plain text for further processing like grammar checking or plain translating. But do not expect to get the translation back in their prior format. The translator needs to be well-tailored for that format.

**Comment by soimort** [comment]
(Correction: I overlooked your punctuation marks part in the suggestion, but the positioning issue still holds.)

Consider a sentence written in basic Markdown markup:
```
$S$ V $O$.
```
By removing those markup signs, you will get:
```
S V O.
```
And it translates to something like (in another language)
```
X Y Z。
```
You could assume that `S` => `X`, and `O` => `Z`, so the result in Markdown markup would be
```
$X$ Y $Z$。
```
But this could be completely wrong, since not every language follows the S-V-O word order. Even worse for the situation, some languages (e.g., Japanese) do not even use whitespaces to split words from XYZ!

In general, there is no easy and correct way to keep the markup format throughout the translation IMHO.

**Comment by Konfekt** [comment]
Thank you for referencing `pandoc` that has a plain text output format.
For future reference, this Vim alias that pipes the output of pandoc converting to plain text file into `translate-shell`:
```vim
Alias -range pt !pandoc\ --from\ <c-r>=&l:filetype<cr>\ --to\ plain\ |\ translate\ -no-warn\ -no-ansi\ -brief\ -to\ <c-r>=&l:spelllang<cr><c-b><c-right><c-right>
```

**Comment by soimort** [comment]
Oh yeah. If the markup notation is not meant to be preserved after the translation, then piping Markdown through `pandoc` then `trans` would certainly be the Unix way of doing it; )

**Comment by Konfekt** [comment]
In case it is meant to be preserved, this looks to complicated to ask for as a feature request (as `plain` is a one-way output format).

**Comment by soimort** [comment]
Agreed. While `markdown -> plain` is easily achieved with an external tool like pandoc, it's a one-way transformation. On the other hand, `markdown -> markdown`, as I firstly thought what you were asking for in this request, requires prior linguistic knowledge and does not always seem feasible, e.g., if someone wants to translate the markdown text "`*I* have a problem`" into Spanish markdown, then the italic markup can't go anywhere properly in the output "`Tengo un problema`".
