### ISSUE TITLE
Bing API broken

### ISSUE THREAD

**Issue by Shatur** [soimort/translate-shell#311]
All Bing API does not work:
```bash
trans -e bing hello
[ERROR] 404 Not Found
trans -e bing -p hello
[ERROR] 404 Not Found
trans -e bing -s hello # Hangs and does not display anything :(
```

My info:
```
trans -V
Translate Shell       0.9.6.9

platform              Linux
gawk (GNU Awk)        4.2.1
fribidi (GNU FriBidi) 1.0.5
audio player          mpv --no-config
terminal pager        less
terminal type         xterm-256color
user locale           ru:en_GB (Emoji)
home language         emj
source language       auto
target language       emj
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]
```

**Comment by Shatur** [comment]
Maybe Bing closed this free API? I can't find anything about it.
Where you read about this API?

**Comment by soimort** [comment]
> `trans -e bing hello`

should be fixed in the latest `develop` branch.

> `trans -e bing -p hello`

For text-to-speech, MS now checks per user access token for authentication, which requires a [non-free subscription key](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-python-text-to-speech#set-the-subscription-key-and-create-a-prompt-for-tts). I might not be able to fix this at the moment.

> `trans -e bing -s hello` 

FYI. This is not a valid command-line usage of `trans`.

**Comment by Shatur** [comment]
Thank you!
