### ISSUE TITLE
blank output 

### ISSUE THREAD

**Issue by TunnelThruTime** [soimort/translate-shell#327]
after using -show-languages n -show-alternative n -i filename in a script,
translate-shell doesn't output text any longer, even after restoring each param back to yes. 
I'm not sure if there where being stored as defaults and I changed that. 
I'd like to know if I can restore the defaults if that is the case. 
The only clue is that there are escape sequences ESC[1mESC[22m 
when I use -view option. 
I'm not knowledgeable enough to know what those escape sequences mean however.

**Comment by soimort** [comment]
Blank output often indicates that your IP address has been blocked by Google due to too many requests.

Try to switch to Bing, or wait a few hours before making the next request.

**Comment by Shamaoke** [comment]
There should be some indication about what's going on to prevent user's confusion.

**Comment by soimort** [comment]
> There should be some indication about what's going on to prevent user's confusion.

Good idea. I'll add a warning message when server returns 403, for future cases.

**Comment by ipstone** [comment]
I was searching for the reason for this behavior (as I am translating a relatively large file) - is it because currently `trans` translate line by line, so that I quickly ran to this behavior? 

It might be good to break large files into 'chunks' to run the query to google translate? and Perhaps adding some 'time-out' feature to prevent this behavior from happening?

Thanks for creating and maintaining this tool, it's really helpful!
