### ISSUE TITLE
bug? Different result from direct google or using Oxford dict

### ISSUE THREAD

**Issue by pwyq** [soimort/translate-shell#335]
When I searched the word `castigate`, the results are totally different.
![Screenshot from 2020-02-07 18-06-27](https://user-images.githubusercontent.com/14853314/74072435-d0036800-49d4-11ea-9938-8f3182731bcf.png)

**Comment by soimort** [comment]
Google Search and Google Translate (https://translate.google.com/) are kind of separate products. You should not expect them to return identical results. translate-shell is a faithful interface for Google Translate (rather than Google Search).

That is to say, the weird "won" thing is exactly what you'll get on https://translate.google.com, when setting the source to "Detect language". If you want Google Translate to translate it correctly, the source language must be explicitly specified as English. (both for the web interface and `trans`)

**Comment by pwyq** [comment]
> Google Search and Google Translate (https://translate.google.com/) are kind of separate products. You should not expect them to return identical results. translate-shell is a faithful interface for Google Translate (rather than Google Search).
> 
> That is to say, the weird "won" thing is exactly what you'll get on https://translate.google.com, when setting the source to "Detect language". If you want Google Translate to translate it correctly, the source language must be explicitly specified as English. (both for the web interface and `trans`)

Thanks, that makes sense. I didn't notice translate-shell auto detected `castigate` as "Romanian".
