### ISSUE TITLE
Google Translate freezes on words like "inch", "in" (due to undesirable synonym data)

### ISSUE THREAD

**Issue by cemelcemelcemel** [soimort/translate-shell#344]
1)
trans en:ru inch
2)
Translate Shell       0.9.6.11

platform              Linux
terminal type         xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        5.0.1
fribidi (GNU FriBidi) 1.0.9
audio player          mpv --no-config
terminal pager        less
web browser           xdg-open
user locale           ru_RU.utf8 (Russian)
home language         ru
source language       auto
target language       ru
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
ip version            [DEFAULT]
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues

Majaro linux

**Comment by soimort** [comment]
Thanks for the report.

It seems that the freeze happens only on some words (`in`, `inch`), but not on others (`out`, `mile`). I'll investigate into this issue.

**Comment by soimort** [comment]
There seems to be a strange bug in Google Translate. When you translate "inch" or "in", a large amount of irrelevant words appear in their "Synonyms" section, they're not even synonyms and completely nonsense.

translate-shell's JSON parser is slow (because it's written in Awk), that's why it takes forever to parse these things...
![thumbnail_Screenshot_20200417-120438](https://user-images.githubusercontent.com/342945/79559633-5c519b80-80a6-11ea-9971-7c8f781925c4.png)

**Comment by soimort** [comment]
Fixed by Google now.
