### ISSUE TITLE
Mac Automator issue

### ISSUE THREAD

**Issue by gonzodude** [soimort/translate-shell#380]
Getting this error The action “Run Shell Script” encountered an error: “/usr/local/trans: line 5713: gawk: command not found” gawk installed on macos

Translate Shell       0.9.6.12-release

platform              Darwin
terminal type         xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        5.1.0
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          [NOT INSTALLED]
terminal pager        less
web browser           open
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
ip version            [DEFAULT]
theme                 default
init file             [NONE]

**Comment by soimort** [comment]
I have no experience with Mac Automator and I don't use Mac -- Sorry I can't help.

I suggest googling "Mac Automator gawk" and see what needs to be done so that Automator can recognize gawk. If gawk is installed by homebrew, then double check whether Automator has access to the path `/usr/local/bin`, where gawk exists. (Based on Homebrew's information on https://docs.brew.sh/FAQ#my-mac-apps-dont-find-usrlocalbin-utilities, it seems GUI apps on macOS don’t have `/usr/local/bin` in their PATH by default. If this is the case, you can fix it by following the instruction on that page)
