### ISSUE TITLE
Man page not installed

### ISSUE THREAD

**Issue by slcott** [soimort/translate-shell#40]
There's no man page installed on my system. I installed via homebrew.

```
scotts-imac:~ lisa$ trans -m
groff: invalid option -- D
usage: groff [-abceghilpstvzCENRSUVXZ] [-Fdir] [-mname] [-Tdev] [-ffam]
       [-wname] [-Wname] [-Mdir] [-dcs] [-rcn] [-nnum] [-olist] [-Parg]
       [-Larg] [-Idir] [files...]
groff -h gives more help
sh: line 0: echo: write error: Broken pipe
scotts-imac:~ lisa$ 
scotts-imac:~ lisa$ man trans
No manual entry for trans
scotts-imac:man lisa$ ls /usr/local/share/man/man* | grep trans
scotts-imac:man lisa$ 
```

**Comment by soimort** [comment]
It seems the default `groff` program shipped with OS X is quite outdated (version 1.19.2). The [new encoding option](http://git.savannah.gnu.org/cgit/groff.git/commit/?id=d0c47148c022daddf4eca49505a0607bc9612b34) -D requires at least groff version 1.20 to run. This is now fixed in master.

Our brew formula doesn't include a man page - and we shall have that very soon.
