### ISSUE TITLE
trans dont work

### ISSUE THREAD

**Issue by fcanlnony** [soimort/translate-shell#461]
![图片](https://user-images.githubusercontent.com/76856769/193172993-bfcdacff-73e0-4476-8b3d-fe2a087bfe08.png)

**Comment by soimort** [comment]
Check if you can actually visit https://translate.google.com/ from the browser, and check the output of  `curl -I https://translate.google.com/`. This is most likely because either your IP has been blocked by Google or you're hitting a firewall.

FYI According to some sources, they're shutting down the translate service in China too. So you will probably need a proxy. https://www.solidot.org/story?sid=72923
