### ISSUE TITLE
I can't use -play and -speak options together in the same time! 

### ISSUE THREAD

**Issue by mostafa20220** [soimort/translate-shell#491]
I run the following command:
`trans -play -speak -b -s en -t ar "boy"`

It works well and everything is great, but only the -speak option work, not both -speak and -play.
Is this how the program supposed to work, or it's a problem with my machine?

I really appreciate any help you can provide.

Here is my info:
```
trans -V
Translate Shell       0.9.7-git:a3bba39

platform              Linux
terminal type         xterm-color
bi-di emulator        konsole
gawk (GNU Awk)        5.2.2
fribidi (GNU FriBidi) 1.0.12
audio player          mpv --no-config
terminal pager        less
web browser           firefox
user locale           en_US.UTF-8 (English)
host language         en
source language       auto
target language       en
translation engine    auto
proxy                 [NONE]
user-agent            Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36 Edg/104.0.1293.54
ip version            [DEFAULT]
theme                 default
init file             [NONE]

```

**Comment by soimort** [comment]
The `-play` and `-speak` are not supposed to be used together, since in the verbose (default) mode `-play` already includes both the original and the translated text:
```
trans -play -s en -t ar "boy"
```

A latter option will always override the former one, so in this case `-speak` overrides `-play`. Currently in the `-b` mode there is no way to pronounce both words in one single command.

**Comment by mostafa20220** [comment]
@soimort 
Thank you! 
I am gonna close the Issue now.
