### ISSUE TITLE
Use better table in README.md

### ISSUE THREAD

**Issue by pickfire** [soimort/translate-shell#52]
```
┌─────┬───────────────┐  
│    │              │  
└────┴────────────────┘
```

**Comment by soimort** [comment]
Could you please attach a screenshot? They looked fine on my browser. Or are you referring to the terminal display?

**Comment by pickfire** [comment]
![table](https://cloud.githubusercontent.com/assets/4687791/7323752/8be738f4-eae3-11e4-876a-84d1addb494f.png)

**Comment by soimort** [comment]
@pickfire I'm sorry. What do you mean?

**Comment by pickfire** [comment]
Those spaces between the vertical bars.

**Comment by soimort** [comment]
I see. This table was exported directly from the output of `trans -R`. On terminal they are vertically connected while on the web they don't render so perfectly due to mismatching `font-size` and `line-height`.

Converting to a GFM-based table might be a good idea, but it's there really just for the purpose of quick reference. I'm not bothered by this, anyway.

![screenshot from 2015-04-26 09 35 12](https://cloud.githubusercontent.com/assets/342945/7335679/45e6a8de-ec01-11e4-9eae-154b44c9bd2a.png)

**Comment by pickfire** [comment]
There is another way to view this table, instead of using markdown, use restructured text as it is another lightweight markup language. Just change **.md** to **.rst**. And

```
┌────┬───────────────┐  
│    │               │  
└────┴───────────────┘
```

to

``` rst
+------------+--------------------+
+            |                    +
+------------+--------------------+
```

**Comment by soimort** [comment]
We're moving it to [wiki: Languages](https://github.com/soimort/translate-shell/wiki/Languages). Closing.
