### ISSUE TITLE
$TRANS_PROGRAM has grown too large for OS X

### ISSUE THREAD

**Issue by zmwangx** [soimort/translate-shell#57]
For the latest commits on the `develop` branch, I get the following error on OS X 10.10.3 with `bash 4.3.33(1)` installed via Homebrew:

``` bash
line 3449: /usr/local/bin/gawk: Argument list too long
```

After a quick bisect, I found the culprit to be 467a56d:

``` bash
> git checkout 467a56d  # develop~7
> make &>/dev/null && build/trans -b hello
build/trans: line 3449: /usr/local/bin/gawk: Argument list too long
> sed -nr "/'EOF'$/,/^EOF/{ /'EOF'$/b; /^EOF/b; p }" build/trans | wc -c  # get the length in bytes of $TRANS_PROGRAM
134262
> git checkout HEAD~1  # develop~8
> make &>/dev/null && build/trans -b hello
hello
> sed -nr "/'EOF'$/,/^EOF/{ /'EOF'$/b; /^EOF/b; p }" build/trans | wc -c
133861
```

The problem appears to be along the line of `MAX_ARG_STRLEN` (not sure about the OS X equivalent), limiting the max length of a single argument, which was once 2^17=131072 on Linux, but apparently the kernel moved on since I couldn't reproduce the bug on Ubuntu 15.04. The field-tested limit seems to be between 133861 and 134262, which is a little bit mysterious since 131072 is smaller than both. (Did I forget some heredoc quoting rule? Probably). At any rate, there's clearly a limit on the length of a single argument on OS X around 2^17, and `$TRANS_PROGRAM` is on the edge of exceeding it.

**Comment by soimort** [comment]
Thanks for bringing this issue up - system specific limit is something I wasn't aware of before.

On Linux kernel, the length limitation of a single argument **is indeed** `MAX_ARG_STRLEN` (**131072**) and this has never increased. You can test this easily with the following program:

``` c
#include <stdio.h>
#include <unistd.h>

#define LEN 131071

int main()
{
    char s[LEN + 1];
    int i;
    for (i = 0; i < LEN; i++)
        s[i] = 'x';
    s[LEN] = 0;
    return execl("/usr/bin/expr", "expr", "length", s, (char *)NULL);
}
```

Change `LEN` to `131072`, the `execl()` call shall fail.

Just like you doubted, your estimation of `$TRANS_PROGRAM` isn't very correct. The actual lengths are 122233 and 122634 respectively, both did not exceed the `MAX_ARG_STRLEN` limit on Linux.

```
$ git checkout 467a56
$ make &>/dev/null && . build/trans -V &> /dev/null && expr length "$TRANS_PROGRAM"
122634
$ git checkout HEAD~1
$ make &>/dev/null && . build/trans -V &> /dev/null && expr length "$TRANS_PROGRAM"
122233
```

While Linux kernel does check for validity of erch argument length (https://github.com/torvalds/linux/blob/master/fs/exec.c#L477), the OS X kernel, XNU, as well as other BSD derivatives, does not perform such check for each single argument, so there is no real equivalent to `MAX_ARG_STRLEN`. XNU however, has a limitation on the **maximum length of arguments**, which is

``` c
#define ARG_MAX        (256 * 1024) /* max bytes for an exec function */
```

as defined in `<syslimits.h>`.

It may seem a bit weird that the argument of length 122233 is fine but the one of length 122634 crashes, since both are far less than 262144, even if you count in all other arguments '`gawk`', '`-f`'. However, every OS has its quirks. I did a simple grepping into XNU's source, it seems these spaces are reserved not only for `argv[]`, but also for `envv[]` (http://www.opensource.apple.com/source/xnu/xnu-2782.1.97/bsd/kern/kern_exec.c , see L#3137-3330). I guess that's why we can't have a lengthier argument in its `execve()` call.
(Not familiar with BSD implementation, so far it's really just a guess. Any experts?)

I cannot tell at exactly what length `$TRANS_PROGRAM` could break on OS X; it is not solely about a single argument length, unlike Linux, as I explained above. Two straightforward solutions I can think of at the moment:
1. Abandon the lengthy argument wrapping; use shell built-in `print` to pipe the whole program to gawk. (I bet shell can take infinite arguments, as long as it's not a system call)
2. Reduce the size of the core program and keep it to 100KB or below.

**Comment by zmwangx** [comment]
Thanks for the clarification; I didn't expect env vars to be counted against `ARG_MAX`. Given that I'd go for shell builtins (yeah, as far as I know they are not limited by `ARG_MAX`). Speaking of limiting the program size, it's still possible to exceed `ARG_MAX` if a user in addition exports some long env vars (albeit unlikely).

**Comment by soimort** [comment]
Due fix in [develop](https://github.com/soimort/translate-shell/tree/develop). Closing.
