### ISSUE TITLE
Fish: #!/usr/bin/gawk -f  \n  ^ invalid char 'n expression  

### ISSUE THREAD

**Issue by ElijahLynn** [soimort/translate-shell#89]
fish, version 2.2.0-377-gdf3da55 

```
$: gawk -f (curl -Ls git.io/translate | psub) -shell      
gawk: /tmp/user/1000/.psub.KyCkqOeqhV:1: #!/usr/bin/gawk -f                                       
gawk: /tmp/user/1000/.psub.KyCkqOeqhV:1: ^ invalid char 'n expression                             
```

**Comment by soimort** [comment]
It has to be something with your `~/.config/fish` customization - sorry I can't help (I'm not familiar with fish).
You may start with an empty fish profile, and try to locate in which part the issue occurs.

**Comment by ElijahLynn** [comment]
K, thanks for the direction.

**Comment by ElijahLynn** [comment]
@soimort I see that you added that Fish example to the readme. Do you know if it worked previously?

**Comment by soimort** [comment]
@ElijahLynn Yes, it works all the time, with my fish 2.2.0.

fish is not my working shell, so you'll need to figure out if it works **without your customization**.

**Comment by ElijahLynn** [comment]
Thanks for confirming. Also, what OS are you on? May I also ask what version of gawk you are using?

I am using Ubuntu 14.40 and GNU Awk 4.0.1.

Thanks

**Comment by soimort** [comment]
@ElijahLynn Does a clean fish profile _work for you, or not_?

**Comment by ElijahLynn** [comment]
Sorry, no it doesn't appear that way, I get the same error if I rename my config.fish to config.fish.bak. The error is gawk saying that it doesn't like what is on line 1. Line 1 is just `#!/usr/bin/gawk -f` and the `^` appears to mean maybe it is talking about the beginning of the line. And then I am not sure what `'n` would signify as well.

I am wondering if maybe it doesn't like that line in an Awk file.

**Comment by soimort** [comment]
Could you just try the installed version, or reproduce the issue in another shell (bash, zsh)? We need to rule out any quirks of a specific shell, so we can know if the problem is really on gawk itself or not.

Note that `gawk -f (curl -Ls git.io/translate | psub) -shell` is just a shortcut for new users to try things out - I don't expect many people would use `trans` this way.

Just for the record,

![screenshot from 2015-11-12 01-10-57](https://cloud.githubusercontent.com/assets/342945/11107073/8a7ac798-88da-11e5-8de7-ab7a9518b2b1.png)

(with the latest git version of fish and zero configuration)
